---
title: "13. Multiple linear regression: model building (part 1)"
subtitle: "Notes and in-class exercises"
format: 
  html:
    embed-resources: true
    toc: true
eval: false # change this to "true" if you want to render a complete .qmd         
---

# Notes

- You can download a template file to work with [here](../activity_templates/13_mlr_model_building_1.qmd).
- **File organization:** Save this file in the "Activities" subfolder of your "STAT155" folder.

## Learning goals

By the end of this lesson, you should be able to:

- Iterate on a broach research question to make it more precise and answerable
- Choose appropriate models for addressing a research question

## Readings and videos

Please watch the following video **before** class.

- Video: [Causal Diagrams and Confounding Variables](https://voicethread.com/share/15362352/)

<!-- This section is for any mini-lecture, review material, material to motivate today's lesson, more guided / structured examples than the exercises section below. -->

# Exercises

## Exercise 1: Descriptive research questions

Consider the following 2 research questions:

1. What are the average home prices in different neighborhoods of St. Paul, MN in 2023?
2. How have rental prices in St. Paul changed over the past five years?

For each question, answer the following:

- Who would be interested in the answer to this question?
- What variables would we need in a dataset to address this question?
- What model(s), plot(s), and or data summaries would be appropriate to use to address this question and why?
    - For models, write the model formula, and indicate which coefficient(s) is/are of interest.
    - For plots, describe the type of plot and what variables are linked to the axes and possibly other features (like point shape and color).
    - For data summaries, describe the summary statistics and groupings you would use.

Why do you think the questions here are often called **descriptive** research questions? Were concepts of confounders, precision variables, effect modifiers, mediators, and/or colliders relevant here? If so, where and why?



## Exercise 2: Predictive research questions

Consider the following 2 research questions:

1. Can we predict the likelihood of a property being sold within 30 days of listing based on its listing details and property characteristics?
2. Can we predict how much over or under the listing price a property will be sold for based on its listing details and property characteristics?

For each question, answer the following:

- Who would be interested in the answer to this question?
- What variables would we need in a dataset to address this question?
- What model(s), plot(s), and or data summaries would be appropriate to use to address this question and why?
    - For models, write the model formula, and indicate which coefficient(s) is/are of interest.
    - For plots, describe the type of plot and what variables are linked to the axes and possibly other features (like point shape and color).
    - For data summaries, describe the summary statistics and groupings you would use.

How do predictive research questions differ from descriptive research questions? Were concepts of confounders, precision variables, effect modifiers, mediators, and/or colliders relevant here? If so, where and why?



## Exercise 3: Causal research questions

Consider the following 2 research questions:

1. Does proximity to highly-rated schools raise home prices?
2. How much does the renovation of a property (e.g., adding a new bathroom or kitchen) affect its market value?

For each question, answer the following:

- Who would be interested in the answer to this question?
- What variables would we need in a dataset to address this question?
- What model(s), plot(s), and or data summaries would be appropriate to use to address this question and why?
    - For models, write the model formula, and indicate which coefficient(s) is/are of interest.
    - For plots, describe the type of plot and what variables are linked to the axes and possibly other features (like point shape and color).
    - For data summaries, describe the summary statistics and groupings you would use.

How do causal research questions differ from predictive and descriptive questions? Were concepts of confounders, precision variables, effect modifiers, mediators, and/or colliders relevant here? If so, where and why?



## Exercise 4: Cultivating curiosity

Think about the role that housing plays in your life right now or may play in the future. What other questions might you have about housing data that haven't come up in the previous exercises? Do these questions seem descriptive, predictive, or causal in nature?





## Reflection

Today was all about letting good questions lead the way and using questions to guide the way we explore data. How confident do you feel about running with questions that come up in your daily life and thinking about what data would answer them and how they would be answered? What might help you feel more confident?

> **Response:** Put your response here.



## Render your work

- Click the "Render" button in the menu bar for this pane (blue arrow pointing right). This will create an HTML file containing all of the directions, code, and responses from this activity. A preview of the HTML will appear in the browser.
- Scroll through and inspect the document to check that your work translated to the HTML format correctly.
- Close the browser tab.
- Go to the "Background Jobs" pane in RStudio and click the Stop button to end the rendering process.
- Navigate to your "Activities" subfolder within your "STAT155" folder and locate the HTML file. You can open it again in your browser to double check.

<br><br><br><br><br><br>

[Solutions](../solutions/13_mlr_model_building_1.qmd)

