project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "!activity_templates/"
    - "!assignments/"
  # post-render: "cp -r activity_templates docs/"
  resources:
    - "data/*.csv"
    - "activity_templates/*.qmd"
    - "assignments/*.qmd"

website:
  title: "STAT 155"
  navbar:
    background: primary
    search: true
    left:
      - file: index.qmd
        text: "Home"
      - file: syllabus.qmd
        text: "Syllabus"
      - file: schedule.qmd
        text: "Schedule"
      - sidebar:activities
      - file: assignments.qmd
        text: "Practice Problems"
      - file: project.qmd
        text: "Project"
      - file: tech_setup.qmd
        text: "Tech Setup"

  sidebar:
    - id: activities
      title: "Activities"
      contents:
        - "activities/01_foundations_welcome.qmd"
        - "activities/02_foundations_univariate.qmd"
        # - 02-adv-ggplot.qmd
        # - 03-file-org-github.qmd
        # - 04-adv-maps.qmd
        # - 05-interactive-viz.qmd
        # - 06-wrangling-1.qmd
        # - 07-wrangling-2.qmd
        # - 08-missing-data.qmd
        # - 09-functions.qmd
        # - 10-subset-str-shiny.qmd
        # - 11-iteration-1.qmd
        # - 12-iteration-2.qmd
        # - 13-apis.qmd
        # - 14-scraping.qmd
        # - 15-strategies-principles.qmd
        # - 16-databases.qmd
        # - 17-joins.qmd
        # - 18-project-work.qmd

    # - id: homework
    #   title: "Homework"
    #   contents:
    #     - "assignments"
    
    # - id: skills_sessions
    #   title: "Skills Sessions"
    #   contents:
    #     - skills_session1.qmd
    #     - skills_session2.qmd
  
  page-footer:
    left: |
      &copy; Jedidiah Carlson, 2024<br>
      All content licensed under ![](https://static.thenounproject.com/png/70967-200.png){height=20px} ([CC BY-NC-SA 4.0](http://creativecommons.org/licenses/by-nc-sa/4.0/))
    right: |
      Site built with [Quarto](https://quarto.org/)

format:
  html:
    theme: solar
    css: styles.css
    toc: true
    code-overflow: wrap

editor: source
