---
title: ""
sidebar: false
---

# STAT 155: Introduction to Statistical Modeling

Macalester College, Fall 2024

<div style="font-size: 20px;">Learn the fundamentals of summarizing, visualizing, and modeling data to answer research questions.</div> <br>

**Instructor:** [Jedidiah Carlson](https://jedidiahcarlson.com) <br>
**Class meeting times:** 

- **Section 05**: Tu/Th 1:20-2:50pm
- **Section 06**: Tu/Th 3:00-4:30pm

**Class location:** THEATR 202 <br>

**Instructor drop-in hours:**

- **location**: My office (OLRI 235)
- **times**: See [this calendar](https://calendar.google.com/calendar/u/5?cid=Y19iZmU1MWU2MGYyY2U0MzQxZTY1MGE3YjUyNzI0NWUyNjRmMzg0MmQxNDVkNTY4NWMxNTEyMGVlNjM2MmQ5ZGEwQGdyb3VwLmNhbGVuZGFyLmdvb2dsZS5jb20) (Tentatively from **1-3pm on Wednesdays** and **10am-11am on Thursdays**, but subject to change based on responses to the introductions survey).
- **1:1 appointments**: I'm also happy to meet one-on-one if my normal drop-in hours don't work for you. You can schedule a time to meet with me using [this link](https://calendar.google.com/calendar/u/0/appointments/schedules/AcZssZ0pNmQwIYzKQcogC3cRSjfg9gDZvzT8Bk_LqXnsmO8NYA0vRJBoz_wGl4IXfk3vxIreKIqA2vbW).

## Course Schedule & Announcements

::: {.callout-tip icon=false collapse="true" title="Week 1: 9/2 - 9/6 (Data fundamentals, univariate visualization and summaries)"}

#### Announcements

Welcome (back) to campus!

#### Tuesday

Before class:

- review the [course syllabus](syllabus.qmd) 
- complete the [Introductions survey](https://forms.gle/mXYCQfrz7Qryk1vW8)
- try [downloading R and RStudio](tech_setup.qmd)


#### Thursday

Before class:

- [Download and familiarize yourself with R and RStudio](tech_setup.qmd)
- Complete the [Introductions survey](https://forms.gle/mXYCQfrz7Qryk1vW8) (if you haven’t already!)
- Complete today’s checkpoint on Moodle
  - Do either the readings or videos for the Day 2 Activity (see Moodle for links)
  - due 30 minutes before class on 9/5

:::


::: {.callout-tip icon=false collapse="false" title="Week 2: 9/9 - 9/13 (Simple linear regression)"}

#### Announcements

- Practice Problems #1 will be due on Friday, 9/13 at 5pm!
- Friday, 9/13 is also the add/drop deadline
- Preceptor office hours start this week--see the course calendar for times

#### Tuesday

Before class:

- Complete today’s checkpoint on Moodle
  - Do either the readings or videos for the Day 3 Activity (see Moodle for links)
  - due 30 minutes before class on 9/10


#### Thursday

Before class:

- Complete today’s checkpoint on Moodle
  - Do either the readings or videos for the Day 4 Activity (see Moodle for links)
  - due 30 minutes before class on 9/12

:::

::: {.callout-tip icon=false collapse="true" title="Week 3: 9/16 - 9/20 (Simple linear regression: model evaluation and variable transformations)"}

#### Announcements

#### Tuesday

#### Thursday

Library data discovery day!

:::

::: {.callout-tip icon=false collapse="true" title="Week 4: 9/23 - 9/27 (Simple linear regression: categorical predictors)"}

#### Announcements

#### Tuesday

#### Thursday

Quiz 1 (1 hour in class)

:::

::: {.callout-tip icon=false collapse="true" title="Week 5: 9/30 - 10/4 (Multiple linear regression: confounding)"}

#### Announcements

#### Tuesday

#### Thursday

:::

::: {.callout-tip icon=false collapse="true" title="Week 6: 10/7 - 10/11 (Multiple linear regression: interaction)"}

#### Announcements

#### Tuesday

#### Thursday

:::

::: {.callout-tip icon=false collapse="true" title="Week 7: 10/14 - 10/18 (Multiple linear regression: model building) (Fall Break)"}

#### Announcements

#### Tuesday

#### Thursday

:::

::: {.callout-tip icon=false collapse="true" title="Week 8: 10/21 - 10/25 (Logistic regression)"}

#### Announcements

#### Tuesday

#### Thursday

:::

::: {.callout-tip icon=false collapse="true" title="Week 9: 10/28 - 11/1 (Tools for statistical inference)"}

#### Announcements

#### Tuesday

#### Thursday

:::

::: {.callout-tip icon=false collapse="true" title="Week 10: 11/4 - 11/8 (Confidence intervals)"}

#### Announcements

#### Tuesday

#### Thursday

:::

::: {.callout-tip icon=false collapse="true" title="Week 11: 11/11 - 11/15 (Hypothesis testing)"}

#### Announcements

#### Tuesday

#### Thursday

:::

::: {.callout-tip icon=false collapse="true" title="Week 12: 11/18 - 11/22 (Hypothesis testing)"}

#### Announcements

#### Tuesday

#### Thursday

:::

::: {.callout-tip icon=false collapse="true" title="Week 13: 11/25 - 11/29 (Hypothesis testing, p-values) (Thanksgiving Break)"}

#### Announcements

#### Tuesday

#### Thursday

:::

::: {.callout-tip icon=false collapse="true" title="Week 14: 12/2 - 12/6 (Project work)"}

#### Announcements

#### Tuesday

#### Thursday

:::

::: {.callout-tip icon=false collapse="true" title="Week 15: 12/9 - 12/13 (Project work, paper, and presentations)"}
#### Announcements

#### Tuesday

(Last day of class)

:::

If you find any typos, bugs, dead links, or have other questions, please email <jcarls13@macalester.edu>